version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
    cooldown:
      default-days: 7
  - package-ecosystem: uv
    directory: /cloudflare
    schedule:
      interval: monthly
      time: "12:00"
    groups:
      runtime:
        dependency-type: "production"
      development:
        dependency-type: "development"
    cooldown:
      default-days: 7
  - package-ecosystem: uv
    directory: /proxmox
    schedule:
      interval: monthly
      time: "12:00"
    groups:
      runtime:
        dependency-type: "production"
      development:
        dependency-type: "development"
    cooldown:
      default-days: 7
  - package-ecosystem: terraform
    directory: /portainer
    schedule:
      interval: monthly
      time: "12:00"
    cooldown:
      default-days: 7
