version: "3"

vars:
  ROOT_DIR: "{{.TASKFILE_DIR}}"
  TF_DIR: "{{.ROOT_DIR}}/homelab"
  DOCKER_PATH: "{{ .DOCKER_PATH | default (toSlash .TASKFILE_DIR) }}" # use repo dir for docker mounts; allow override

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list

  install:
    desc: Terraform init (homelab)
    cmds:
      - terraform -chdir="{{.TF_DIR}}" init

  validate:
    desc: Terraform validate (homelab)
    cmds:
      - terraform -chdir="{{.TF_DIR}}" validate

  format:
    desc: Run terraform fmt -recursive
    cmds:
      - terraform fmt -recursive

  format-check:
    desc: Check formatting without changing files
    cmds:
      - terraform fmt -recursive --check

  lint:
    desc: Run tflint across the repo
    cmds:
      - docker run --rm -v "{{.DOCKER_PATH}}:/data" -t ghcr.io/terraform-linters/tflint --chdir /data --recursive

  checkov:
    desc: Run checkov misconfiguration scan
    cmds:
      - docker run --rm -v "{{.DOCKER_PATH}}:/tf" --workdir /tf -t bridgecrew/checkov --directory /tf

  kics:
    desc: Run kics misconfiguration scan
    cmds:
      - docker run --rm -v "{{.DOCKER_PATH}}:/path" -t checkmarx/kics scan -p /path -o "/path/"

  trivy:
    desc: Run trivy filesystem misconfiguration scan
    cmds:
      - docker run -v "{{.DOCKER_PATH}}:/app" aquasec/trivy fs --scanners misconfig /app

  secure:
    desc: Aggregate security scans (trivy, checkov, kics)
    deps:
      - trivy
      - checkov
      - kics

  check:
    desc: Validate, format, lint, and run security scans
    deps:
      - validate
      - format
      - lint
      - secure
