name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ghas-infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@infra-scan-v0

  terraform-ci:
    uses: notdodo/github-actions/.github/workflows/terraform-ci.yml@terraform-ci-v0
