name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ghas-infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-scan:
    permissions:
      actions: read
      security-events: write
      pull-requests: write
      contents: read
      id-token: write
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@infra-scan-v0

  terraform-ci:
    permissions:
      actions: read
      security-events: write
      contents: read
      id-token: write
    uses: notdodo/github-actions/.github/workflows/terraform-ci.yml@terraform-ci-v0
    with:
      aws-role: arn:aws:iam::841162699174:role/proxmox-terraform-readonly
