name: Terraform CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ghas-tf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-ci:
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      id-token: write
    uses: notdodo/github-actions/.github/workflows/terraform-ci.yml@terraform-ci-v0
    with:
      aws-role: arn:aws:iam::841162699174:role/proxmox-terraform-readonly
    secrets:
      sops-decryption-key: ${{ secrets.AGE_KEY }}
